using System.Collections;
using Behind_Bars.Helpers;
using UnityEngine;
using MelonLoader;
#if !MONO
using Il2CppScheduleOne.PlayerScripts;
#else
using ScheduleOne.PlayerScripts;
#endif

namespace Behind_Bars.Systems
{
    /// <summary>
    /// Compatibility shell for the planned court, negotiation, and sentencing flow.
    /// </summary>
    /// <remarks>
    /// The public entry point currently runs a scripted coroutine with placeholder UI and no
    /// player-input path. Negotiation therefore expires with its success flag false, and final
    /// sentencing hands the resulting amount to <see cref="BailSystem"/> when available. This
    /// class is not yet a complete court authority or persisted court-session system.
    /// </remarks>
    public class CourtSystem
    {
        // Unity-scaled seconds available to the placeholder negotiation loop.
        private const float NEGOTIATION_TIME_LIMIT = 60f;
        // Lowest allowed negotiated amount as a fraction of the original bail.
        private const float MIN_NEGOTIATION_AMOUNT = 0.5f;
        
        /// <summary>Phase currently represented by a scripted court session.</summary>
        public enum CourtPhase
        {
            /// <summary>Initial bail is presented.</summary>
            InitialBail = 0,
            /// <summary>Negotiation window is active.</summary>
            Negotiation = 1,
            /// <summary>Final amount and notes are selected.</summary>
            FinalDecision = 2,
            /// <summary>Sentencing/payment handoff is performed.</summary>
            Sentencing = 3
        }

        /// <summary>
        /// In-memory state passed between the scripted court phases.
        /// </summary>
        public class CourtSession
        {
            /// <summary>Player represented by the session.</summary>
            public Player Defendant { get; set; }
            /// <summary>Original bail amount presented at the start.</summary>
            public float OriginalBailAmount { get; set; }
            /// <summary>Current amount used by the placeholder negotiation phase.</summary>
            public float CurrentBailAmount { get; set; }
            /// <summary>Final amount selected by the decision phase.</summary>
            public float NegotiatedAmount { get; set; }
            /// <summary>Current scripted court phase.</summary>
            public CourtPhase CurrentPhase { get; set; }
            /// <summary>Remaining Unity-scaled seconds in the placeholder negotiation window.</summary>
            public float TimeRemaining { get; set; }
            /// <summary>Whether a caller/implementation marked negotiation as successful.</summary>
            public bool IsNegotiationSuccessful { get; set; }
            /// <summary>Judge-facing notes generated by the decision/scaffold path.</summary>
            public string JudgeNotes { get; set; } = "";
        }

        /// <summary>
        /// Run the scripted court phases for a defendant and bail amount.
        /// </summary>
        /// <param name="player">Defendant entering the court scaffold.</param>
        /// <param name="bailAmount">Initial bail amount presented to the scaffold.</param>
        /// <remarks>
        /// The current path presents placeholder phases, performs no interactive negotiation,
        /// and then attempts bail payment. It does not persist a session or provide a court UI.
        /// </remarks>
        public IEnumerator StartCourtSession(Player player, float bailAmount)
        {
            ModLogger.Info($"Starting court session for {player.name} with bail amount: ${bailAmount}");
            
            var session = new CourtSession
            {
                Defendant = player,
                OriginalBailAmount = bailAmount,
                CurrentBailAmount = bailAmount,
                NegotiatedAmount = bailAmount,
                CurrentPhase = CourtPhase.InitialBail,
                TimeRemaining = NEGOTIATION_TIME_LIMIT
            };
            
            // Start the court sequence
            yield return ConductCourtSession(session);
        }

        /// <summary>
        /// Execute the four scripted phases for one in-memory court session.
        /// </summary>
        /// <param name="session">Session state to mutate across the phases.</param>
        private IEnumerator ConductCourtSession(CourtSession session)
        {
            ModLogger.Info($"Court session beginning for {session.Defendant.name}");
            
            // Phase 1: Initial bail presentation
            yield return PresentInitialBail(session);
            
            // Phase 2: Negotiation (if applicable)
            if (session.CurrentBailAmount > 0)
            {
                yield return ConductNegotiation(session);
            }
            
            // Phase 3: Final decision
            yield return MakeFinalDecision(session);
            
            // Phase 4: Sentencing
            yield return ExecuteSentencing(session);
        }

        /// <summary>
        /// Present the initial bail placeholder and wait for the scripted reading interval.
        /// </summary>
        /// <param name="session">Session whose phase is updated.</param>
        /// <remarks>The planned judge/charge/options UI is not implemented.</remarks>
        private IEnumerator PresentInitialBail(CourtSession session)
        {
            ModLogger.Info($"Presenting initial bail amount: ${session.OriginalBailAmount:F0}");
            
            // TODO: Implement court UI
            // This should show:
            // - Judge's opening statement
            // - Charges against the defendant
            // - Initial bail amount
            // - Options for the player
            
            session.CurrentPhase = CourtPhase.InitialBail;
            
            // Give player time to read
            yield return new WaitForSeconds(3f);
            
            ModLogger.Info("Initial bail presentation complete");
        }

        /// <summary>
        /// Run the placeholder negotiation countdown without player input.
        /// </summary>
        /// <param name="session">Session whose phase, timer, and success flag are updated.</param>
        /// <remarks>
        /// The timer uses Unity-scaled <see cref="Time.deltaTime"/> and yields each frame. No
        /// input/evidence/witness path currently sets success, so this phase ends unsuccessful.
        /// </remarks>
        private IEnumerator ConductNegotiation(CourtSession session)
        {
            ModLogger.Info($"Beginning bail negotiation for {session.Defendant.name}");
            
            session.CurrentPhase = CourtPhase.Negotiation;
            session.TimeRemaining = NEGOTIATION_TIME_LIMIT;
            
            // TODO: Implement negotiation UI
            // This should include:
            // - Timer display
            // - Current bail amount
            // - Negotiation options
            // - Player's negotiation skills display
            
            // Simulate negotiation process
            while (session.TimeRemaining > 0)
            {
                session.TimeRemaining -= Time.deltaTime;
                
                // TODO: Check for player input during negotiation
                // This could include:
                // - Accept current amount
                // - Try to negotiate lower
                // - Present evidence
                // - Call character witnesses
                
                yield return null;
            }
            
            // Negotiation time expired
            ModLogger.Info("Negotiation time expired");
            session.IsNegotiationSuccessful = false;
        }

        /// <summary>
        /// Select the placeholder final bail amount and judge notes.
        /// </summary>
        /// <param name="session">Session whose final decision fields are updated.</param>
        /// <remarks>
        /// A successful flag receives an example 20 percent reduction; the current scripted
        /// negotiation never sets that flag, so the normal public path retains original bail.
        /// The result is clamped to at least 50 percent of the original amount.
        /// </remarks>
        private IEnumerator MakeFinalDecision(CourtSession session)
        {
            ModLogger.Info($"Making final decision for {session.Defendant.name}");
            
            session.CurrentPhase = CourtPhase.FinalDecision;
            
            // Determine final bail amount based on negotiation
            if (session.IsNegotiationSuccessful)
            {
                // TODO: Calculate final amount based on player's negotiation performance
                session.NegotiatedAmount = session.CurrentBailAmount * 0.8f; // 20% reduction as example
                session.JudgeNotes = "The court has considered your arguments and reduced the bail amount.";
            }
            else
            {
                session.NegotiatedAmount = session.OriginalBailAmount;
                session.JudgeNotes = "No successful negotiation was reached. Original bail amount stands.";
            }
            
            // Ensure the amount doesn't go below minimum
            session.NegotiatedAmount = Mathf.Max(session.NegotiatedAmount, 
                                               session.OriginalBailAmount * MIN_NEGOTIATION_AMOUNT);
            
            ModLogger.Info($"Final bail amount: ${session.NegotiatedAmount:F0}");
            
            // TODO: Show final decision UI
            yield return new WaitForSeconds(2f);
        }

        /// <summary>
        /// Run the sentencing placeholder and hand the final amount to bail processing.
        /// </summary>
        /// <param name="session">Session whose phase and judge notes are updated.</param>
        /// <remarks>
        /// No sentencing UI or non-payment consequence is implemented. Missing bail
        /// infrastructure leaves the defendant in custody and only waits briefly before exit.
        /// </remarks>
        private IEnumerator ExecuteSentencing(CourtSession session)
        {
            ModLogger.Info($"Executing sentencing for {session.Defendant.name}");
            
            session.CurrentPhase = CourtPhase.Sentencing;
            
            // TODO: Implement sentencing UI
            // This should show:
            // - Judge's final ruling
            // - Final bail amount
            // - Payment options
            // - Consequences of non-payment
            
            ModLogger.Info($"Court session complete. Final bail: ${session.NegotiatedAmount:F0}");
            
            // Hand off to bail system for payment processing
            var bailSystem = Core.ResolveBailSystem();
            if (bailSystem != null)
            {
                yield return bailSystem.ProcessBailPayment(session.Defendant, session.NegotiatedAmount);
            }
            else
            {
                session.JudgeNotes = "Bail infrastructure was unavailable. Defendant remains in custody until the jail flow can complete.";
                ModLogger.Error($"CourtSystem: BailSystem unavailable for {session.Defendant.name} - leaving defendant in custody and skipping payment handoff");
                yield return new WaitForSeconds(1f);
                yield break;
            }
            
            yield return new WaitForSeconds(1f);
        }

        /// <summary>
        /// Calculate a normalized negotiation-success score from three weighted inputs.
        /// </summary>
        /// <param name="playerSkill">Player negotiation contribution weighted at 30 percent.</param>
        /// <param name="evidenceStrength">Evidence contribution weighted at 40 percent.</param>
        /// <param name="witnessCredibility">Witness contribution weighted at 30 percent.</param>
        /// <returns>The weighted value clamped to the 0-1 range.</returns>
        /// <remarks>This helper is not wired into the placeholder court coroutine.</remarks>
        public float CalculateNegotiationSuccess(float playerSkill, float evidenceStrength, float witnessCredibility)
        {
            // Calculate negotiation success based on multiple factors
            float baseSuccess = playerSkill * 0.3f; // 30% from player skill
            float evidenceBonus = evidenceStrength * 0.4f; // 40% from evidence
            float witnessBonus = witnessCredibility * 0.3f; // 30% from witnesses
            
            float totalSuccess = baseSuccess + evidenceBonus + witnessBonus;
            
            // Clamp between 0 and 1
            return Mathf.Clamp01(totalSuccess);
        }

        /// <summary>
        /// Return a canned judge response for a negotiation-success score.
        /// </summary>
        /// <param name="negotiationSuccess">Score selecting the response band.</param>
        /// <param name="requestedReduction">Requested reduction; currently ignored by the canned responses.</param>
        /// <returns>A player-facing judge response.</returns>
        public string GetJudgeResponse(float negotiationSuccess, float requestedReduction)
        {
            if (negotiationSuccess > 0.8f)
            {
                return "The court is impressed with your argument. We'll consider a significant reduction.";
            }
            else if (negotiationSuccess > 0.6f)
            {
                return "You make some valid points. A moderate reduction may be possible.";
            }
            else if (negotiationSuccess > 0.4f)
            {
                return "Your argument has some merit, but the evidence is not compelling enough for a large reduction.";
            }
            else
            {
                return "The court finds your arguments unconvincing. The original bail amount stands.";
            }
        }
    }
}
